// USER AUTH
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_LOGIN = "AUTH_LOGIN";
export const CLEAR_REGISTER = "CLEAR_REGISTER";
export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const FETCH_USER = "FETCH_USER";
export const USER_UPDATE = "USER_UPDATE";
export const CLEAN_USER_INFO = "CLEAN_USER_INFO";

// Footer
export const FETCH_FOOTER = "FETCH_FOOTER";

// Configurator
export const CHANGE_CONFIGURATOR = 'CHANGE_CONFIGURATOR';

// Cart
export const FETCH_CART = 'FETCH_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const INCREASE_CART_ITEM = 'INCREASE_CART_ITEM';
export const DECREASE_CART_ITEM = 'DECREASE_CART_ITEM';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

// Order
export const CREATE_ORDER = 'CREATE_ORDER';
export const CLEAR_CREATED_ORDER = 'CLEAR_CREATED_ORDER';
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDER = 'FETCH_ORDER';

// Subscriptions
export const FETCH_SUBSCRIPTIONS = 'FETCH_SUBSCRIPTIONS';
export const FETCH_SUBSCRIPTION = 'FETCH_SUBSCRIPTION';
export const CLEAR_SUBSCRIPTION = 'CLEAR_SUBSCRIPTION';