// USER AUTH
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_LOGIN = "AUTH_LOGIN";
export const CLEAR_REGISTER = "CLEAR_REGISTER";
export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const FETCH_USER = "FETCH_USER";
export const USER_UPDATE = "USER_UPDATE";
export const CLEAN_USER_INFO = "CLEAN_USER_INFO";
export const FETCH_ORDERS = "FETCH_ORDERS";

export const FETCH_FOOTER = "FETCH_FOOTER";